### ISSUE TITLE
I can't open file selection window when click on label

### ISSUE THREAD

**Issue by heltonalves99** [Gixx/mdl-kvl#10]
He man, how are you ?
So, I'm using here the same example in website:

<div class="mdl-file mdl-js-file mdl-file--floating-label">
    <input type="file" name="avatar" id="avatar">
    <label class="mdl-file__label" for="avatar">Avatar</label>
</div>

but when I click on avatar label, the selection windows does not open, it open just when I click in Icon.
there is any way to open selection window by clicking in label?

another thing, I want to change the Icon, put other one!
there is any way to do it?

thanks man and congratulations for the project, it's so useful!

**Comment by Gixx** [comment]
Hi,

Maybe I misunderstand something, but you wrote "Avatar", however it seem like you have problem with the file uploader.

**Avatar**: maybe I can add an event for the label later, but was not planned since the avatar image is much bigger, so I don't know who and why would click on the label? 

**File uploader**: it's a very tricky component, I'm thinking on how can I improve it...

But it's a request of yours, so I will do it, as soon as I have time. I tried to provide a fast solution, but I couldn't trigger the proper actions with the right parameters, so I need to add these to the library for both.

For the other problem: what do you mean icon? 

**Avatar**: the "default avatar image" can be edited by the "value" attribute.

**File uploader**: the "attach" button icon can be changed with CSS:
```css
.mdl-file i.material-icons:before {
    /* choose another icon from here: https://material.io/icons/ */
    /* and replace spaces with underscores */
    /* and make sure to put enough spaces after the "icon text" to shift the original content out of the box */
    content: "shopping_cart                            ";
}
```
